services:
  fastapi:
    build:
      context: .
    image: online-course-access-time-cost:dev
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    volumes:
      - .:/app
    working_dir: /app
    command:
      ['uvicorn', 'main:app', '--reload', '--host', '0.0.0.0', '--port', '8000']
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_course_db
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U devuser -d online_course_db']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
