"""Put back fastapi_inserted_data

Revision ID: 636dd10c9da1
Revises: 4ee0864f38b4
Create Date: 2025-09-17 21:10:02.200751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "636dd10c9da1"
down_revision: Union[str, Sequence[str], None] = "4ee0864f38b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fastapi_inserted_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("casovna_znacka", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("poraba", sa.Float(), nullable=True),
        sa.Column("dinamicne_cene", sa.Float(), nullable=True),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"], ["fastapi_stranke.student_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fastapi_inserted_data_id"),
        "fastapi_inserted_data",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fastapi_inserted_data_id"), table_name="fastapi_inserted_data"
    )
    op.drop_table("fastapi_inserted_data")
    # ### end Alembic commands ###
